apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: helm-traefik
spec:
  package: ghcr.io/hops-ops/helm-traefik:{{ .Values.version }}
{{- if .Values.skipDependencyResolution }}
  skipDependencyResolution: true
{{- end }}
{{- if .Values.skipDependencyResolution }}
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: hops-ops-helm-traefikrender
spec:
  package: ghcr.io/hops-ops/helm-traefikrender:{{ .Values.version }}
{{- end }}
